version: "3"

secrets:
  tailscale_authkey:
    file: authkey.txt

services:
  caddy:
    image: erlend/caddy
    command: caddy tailscale-proxy --from=tailscale/grafana:80 --to=grafana:3000
    environment:
      TS_AUTHFILE: /run/secrets/tailscale_authkey
    secrets: [tailscale_authkey]

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
